security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        default:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: lazy
            provider: default
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: logout
                success_handler: App\Security\UserAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
